name: Regenerate Paws Website

on:
  schedule:
    # At 12:00, on day 10 of the month, every 4 months
    # Giving 10 days for paws regen to be approved
    - cron: "0 12 10 */4 *"
  workflow_dispatch:
    inputs:
      text_to_print:
        description: "Manual re-build"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: regen-site

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Get requirements
        run: make requirements

      - name: Update Paws Submodule
        run: |
          make update-deps

      - name: Regen Paws Site
        run: |
          make regen-site

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Regenerate Paws Website"
